"""Unit tests for validators.py — no network, no environment required."""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Allow running without installing the package.
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from common.validators import (
    validate_automation_sessions_rows,
    validate_jobs_final_rows,
)


# ── jobs_final ────────────────────────────────────────────────────────────────

class TestJobsFinalValidator:
    def test_minimal_valid_row(self):
        rows = [{"company_name": "Acme"}]
        result = validate_jobs_final_rows(rows)
        assert len(result) == 1
        assert result[0]["company_name"] == "Acme"

    def test_id_auto_generated_when_omitted(self):
        """id is generated by DB and omitted from normalized payloads."""
        rows = [{"company_name": "Acme"}]
        result = validate_jobs_final_rows(rows)
        assert "id" not in result[0]

    def test_explicit_id_omitted_from_payload(self):
        rows = [{"id": "aaaaaaaa-0000-0000-0000-000000000001"}]
        result = validate_jobs_final_rows(rows)
        assert "id" not in result[0]  # id is filtered out by exclude_none

    def test_explicit_id_preserved_when_requested(self):
        rows = [{"id": "aaaaaaaa-0000-0000-0000-000000000001"}]
        result = validate_jobs_final_rows(rows, preserve_fields=("id",))
        assert result[0]["id"] == "aaaaaaaa-0000-0000-0000-000000000001"

    def test_defaults_applied(self):
        rows = [{"company_name": "Acme"}]
        result = validate_jobs_final_rows(rows)
        assert result[0].get("match_score") is None
        assert result[0].get("language") == "English"
        assert result[0].get("is_deleted") is False
        assert result[0].get("job_status") == "SAVED"

    def test_display_form_normalised_to_uppercase(self):
        rows = [{"job_status": "Resume-Rejected"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_status"] == "RESUME_REJECTED"

    def test_uppercase_preserved(self):
        rows = [{"job_status": "INTERVIEW_REJECTED"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_status"] == "INTERVIEW_REJECTED"

    def test_case_insensitive_status_accepted(self):
        rows = [{"job_status": "saved"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_status"] == "SAVED"

    def test_invalid_job_status(self):
        rows = [{"job_status": "UNKNOWN_STATUS"}]
        with pytest.raises(Exception):
            validate_jobs_final_rows(rows)

    def test_scraped_job_status_valid(self):
        rows = [{"job_status": "SCRAPED"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_status"] == "SCRAPED"

    def test_enriched_job_status_valid(self):
        rows = [{"job_status": "ENRICHED"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_status"] == "ENRICHED"

    def test_epoch_ms_timestamp_normalised(self):
        rows = [{"saved_at": 1743674410421}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["saved_at"].endswith("Z"), "saved_at must be ISO-8601 UTC"

    def test_extra_field_rejected(self):
        rows = [{"unknown_column": "bad"}]
        with pytest.raises(Exception):
            validate_jobs_final_rows(rows)

    def test_all_display_forms_normalise_to_uppercase(self):
        cases = {
            "Saved": "SAVED",
            "Ready-To-Apply": "READY_TO_APPLY",
            "Waiting-Confirmation": "WAITING_CONFIRMATION",
            "Applied": "APPLIED",
            "Interview": "INTERVIEW",
            "Interviewing": "INTERVIEWING",
            "Offer": "OFFER",
            "Resume-Rejected": "RESUME_REJECTED",
            "Interview-Rejected": "INTERVIEW_REJECTED",
        }
        for display, expected in cases.items():
            rows = [{"job_status": display}]
            result = validate_jobs_final_rows(rows)
            assert result[0]["job_status"] == expected, f"{display} should normalise to {expected}"

    def test_ready_to_apply_job_status_valid(self):
        rows = [{"job_status": "READY_TO_APPLY"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_status"] == "READY_TO_APPLY"

    def test_waiting_confirmation_job_status_valid(self):
        rows = [{"job_status": "WAITING_CONFIRMATION"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_status"] == "WAITING_CONFIRMATION"

    def test_valid_decision(self):
        rows = [{"decision": "AUTO_APPROVE"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["decision"] == "AUTO_APPROVE"

    def test_invalid_decision(self):
        rows = [{"decision": "APPROVE"}]
        with pytest.raises(Exception):
            validate_jobs_final_rows(rows)

    def test_valid_user_action(self):
        rows = [{"user_action": "APPROVED"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["user_action"] == "APPROVED"

    def test_invalid_user_action(self):
        rows = [{"user_action": "MAYBE"}]
        with pytest.raises(Exception):
            validate_jobs_final_rows(rows)

    def test_approved_at_epoch_normalised(self):
        rows = [{"approved_at": 1743674410421}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["approved_at"].endswith("Z")

    def test_enrichment_fields_accepted(self):
        rows = [{
            "tech_stack": ["Python", "FastAPI"],
            "experience_level": "Senior",
            "work_mode": "hybrid",
        }]
        result = validate_jobs_final_rows(rows)
        assert result[0]["tech_stack"] == ["Python", "FastAPI"]

    def test_source_platform_allowed(self):
        rows = [{"source_platform": "indeed"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["source_platform"] == "indeed"

    def test_job_type_canonical_value_preserved(self):
        rows = [{"job_type": "fulltime"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_type"] == "fulltime"

    def test_job_type_alias_normalised(self):
        rows = [{"job_type": "Full-Time"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_type"] == "fulltime"

    def test_job_type_unknown_falls_back_to_other(self):
        rows = [{"job_type": "freelance"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["job_type"] == "other"

    def test_work_mode_canonical_value_preserved(self):
        rows = [{"work_mode": "hybrid"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["work_mode"] == "hybrid"

    def test_work_mode_alias_normalised(self):
        rows = [{"work_mode": "On Site"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["work_mode"] == "on-site"

    def test_work_mode_unknown_falls_back_to_other(self):
        rows = [{"work_mode": "field"}]
        result = validate_jobs_final_rows(rows)
        assert result[0]["work_mode"] == "other"

    def test_tags_rejected(self):
        rows = [{"tags": ["python", "fastapi"]}]
        with pytest.raises(Exception):
            validate_jobs_final_rows(rows)


class TestAutomationSessionsValidator:
    def test_minimal_valid_row(self):
        rows = [{"job_id": "aaaaaaaa-0000-0000-0000-000000000001", "automation_type": "JOB_APPLY"}]
        result = validate_automation_sessions_rows(rows)
        assert len(result) == 1
        assert result[0]["job_id"] == "aaaaaaaa-0000-0000-0000-000000000001"
        assert result[0]["automation_type"] == "JOB_APPLY"
        assert result[0]["session_status"] == "RUNNING"

    def test_id_omitted_by_default(self):
        rows = [{"id": "aaaaaaaa-0000-0000-0000-000000000001", "job_id": "bbbbbbbb-0000-0000-0000-000000000001", "automation_type": "JOB_APPLY"}]
        result = validate_automation_sessions_rows(rows)
        assert "id" not in result[0]

    def test_id_preserved_for_upsert_conflict(self):
        rows = [{"id": "aaaaaaaa-0000-0000-0000-000000000001", "job_id": "bbbbbbbb-0000-0000-0000-000000000001", "automation_type": "JOB_APPLY"}]
        result = validate_automation_sessions_rows(rows, preserve_fields=("id",))
        assert result[0]["id"] == "aaaaaaaa-0000-0000-0000-000000000001"

    def test_invalid_automation_type_rejected(self):
        rows = [{"job_id": "aaaaaaaa-0000-0000-0000-000000000001", "automation_type": "OTHER"}]
        with pytest.raises(Exception):
            validate_automation_sessions_rows(rows)

    def test_invalid_session_status_rejected(self):
        rows = [{"job_id": "aaaaaaaa-0000-0000-0000-000000000001", "automation_type": "JOB_APPLY", "session_status": "PAUSED"}]
        with pytest.raises(Exception):
            validate_automation_sessions_rows(rows)

    def test_negative_retry_count_rejected(self):
        rows = [{"job_id": "aaaaaaaa-0000-0000-0000-000000000001", "automation_type": "JOB_APPLY", "retry_count": -1}]
        with pytest.raises(Exception):
            validate_automation_sessions_rows(rows)

    def test_started_at_epoch_normalized(self):
        rows = [{"job_id": "aaaaaaaa-0000-0000-0000-000000000001", "automation_type": "JOB_APPLY", "started_at": 1743674410421}]
        result = validate_automation_sessions_rows(rows)
        assert result[0]["started_at"].endswith("Z")

    def test_extra_field_rejected(self):
        rows = [{"job_id": "aaaaaaaa-0000-0000-0000-000000000001", "automation_type": "JOB_APPLY", "unexpected": "x"}]
        with pytest.raises(Exception):
            validate_automation_sessions_rows(rows)


